### put-hashes
POST {{scheme}}{{host}}:{{port}}/api/v1/hash/put-hashes
Content-Type: application/json

{
  "baseRequest": {
    "key": "hashes key"
  },
  "field": "field one",
  "value": "asd"
}

### get-hash-value
GET {{scheme}}{{host}}:{{port}}/api/v1/hash/get-hash-value?
    key=hashes key&
    field=field one